Update pipeline

diff --git a/.github/workflows/custom-pipeline.yaml b/.github/workflows/custom-pipeline.yaml
--- a/.github/workflows/custom-pipeline.yaml
+++ b/.github/workflows/custom-pipeline.yaml
@@ -9,5 +9,14 @@ jobs:
     steps:
       - name: Simple GET 
         run: |
-          curl --fail-with-body https://api.indexnow.org/indexnow?url=https://dyluc.github.io/&key=73f94957-7684-4cbd-98cc-0a97d3522954 \
-          && echo "✅"
+          response=$(curl -s -o /dev/null -w "%{http_code}" --fail-with-body \
+            "https://api.indexnow.org/indexnow?url=https://dyluc.github.io/&key=73f94957-7684-4cbd-98cc-0a97d3522954")
+
+          echo "HTTP status: $response"
+
+          if [ "$response" -ne 200 ]; then
+            echo "API call failed with status $response"
+            exit 1
+          fi
+
+          echo "POST successful"
